### PR TITLE
completed first objective for carsus atomic data

### PR DESCRIPTION
**Pull request by Chinmay4400**
Completed first objective for project Carsus Atomic Data. Made a module to parse and store atomic data in an hdf file.

## Description
Added a file atomic_data_parse.py containing a function parse_atomic_data to parse and extract atomic data from si2_osc_kurucz file as mentioned in the project objective.
The data is stored in an hdf file as pandas DataFrames.

## How Has This Been Tested?
Added unit test for the function testing the formation of h5 file and checking shapes of resultant DataFrames.

## Screenshots (if appropriate):
Screenshot_20200313_013732

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

Gist for example notebook : https://gist.github.com/Chinmay4400/f1b3a0c9835573647b5dbbebdfec1cce

### CODE REVIEW

**Comment by Chinmay4400** [comment]
@afloers I was not sure where to place the parser module, so I placed it in the root directory for now.

**Comment by Chinmay4400** [comment]
@afloers In my test I'm importing the data file from parent folder of tests. Can you tell me how carsus aims to get the data i.e. from a local directory or remote url, so I can modify the test accordingly.

**Comment by afloers** [comment]
Please add a parser class which can download and read atomic data files. If the atomic data has already been downloaded, it should use the stored data instead.

**Comment by Chinmay4400** [comment]
@afloers where should I put the downloaded data. In the same folder as parser or in a separate folder?

**Comment by afloers** [comment]
Put it in a folder that doesn't get uploaded to github - we don't need to archive it here. Just check if the data is in this folder, and if not, download it from CMFGEN.

**Comment by Chinmay4400** [comment]
@afloers I have made the required changes in the latest commit. I have also added a notebook in carsus/docs/notebooks to demonstrate the use of the parser class.

**Comment by Chinmay4400** [comment]
@afloers Would we be interested in making visualizations to better analyze data that is  parsed?

**Comment by afloers** [comment]
> @afloers Would we be interested in making visualizations to better analyze data that is parsed?

It would be nice, but that would be a something for when the actual project is done. Right now the priority should be to have a parser that can read the various atomic data formats.

**Comment by afloers** [comment]
Can you try other `osc_files`? See if you need to change anything in order to read them.

**Pull request closed without merging**
