### PR TITLE
Fixed requests SSL issue

### LINKED ISSUE #329: Error while downloading NIST dataset
**Describe the bug**
The `NISTWeightsComp` and `NISTIonizationEnergies` functions are unstable and fail at some executions due to `SSLCertVerificationError`. The functions start working again on repeated attempts. The error occurs when the program tries to fetch the data from `https://physics.nist.gov/`. 

**To Reproduce**
1. Configure the project and launch the python shell.
2. Run these commands:
```
from carsus.io.nist import NISTIonizationEnergies
ionization_energies = NISTIonizationEnergies('H-Zn')
```
The `NISTIonizationEnergies()` function can fail randomly.

**System**
 - OS:
    - [x] GNU/Linux
    - [x] macOS

 - Environment (`conda list`): carsus

**Additional context**
Error logs:

```
>>> ionization_energies = NISTIonizationEnergies('H-Zn')
[  carsus.io.nist.ionization][   INFO] - Downloading ionization energies from the NIST Atomic Spectra Database. (ionization.py:64)
Traceback (most recent call last):
  File "/Users/shikha/miniconda3/envs/carsus/lib/python3.7/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/Users/shikha/miniconda3/envs/carsus/lib/python3.7/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/shikha/miniconda3/envs/carsus/lib/python3.7/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/Users/shikha/miniconda3/envs/carsus/lib/python3.7/site-packages/urllib3/connection.py", line 424, in connect
    tls_in_tls=tls_in_tls,
  File "/Users/shikha/miniconda3/envs/carsus/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 450, in ssl_wrap_socket
    sock, context, tls_in_tls, server_hostname=server_hostname
  File "/Users/shikha/miniconda3/envs/carsus/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/shikha/miniconda3/envs/carsus/lib/python3.7/ssl.py", line 423, in wrap_socket
    session=session
  File "/Users/shikha/miniconda3/envs/carsus/lib/python3.7/ssl.py", line 870, in _create
    self.do_handshake()
  File "/Users/shikha/miniconda3/envs/carsus/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/shikha/miniconda3/envs/carsus/lib/python3.7/site-packages/requests/adapters.py", line 499, in send
    timeout=timeout,
  File "/Users/shikha/miniconda3/envs/carsus/lib/python3.7/site-packages/urllib3/connectionpool.py", line 788, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/Users/shikha/miniconda3/envs/carsus/lib/python3.7/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='physics.nist.gov', port=443): Max retries exceeded with url: /PhysRefData/ASD/Html/verhist.shtml (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/shikha/Dev/Proj/carsus/carsus/io/nist/ionization.py", line 319, in __init__
    self._get_version()
  File "/Users/shikha/Dev/Proj/carsus/carsus/io/nist/ionization.py", line 355, in _get_version
    html = requests.get(IONIZATION_ENERGIES_VERSION_URL)
  File "/Users/shikha/miniconda3/envs/carsus/lib/python3.7/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/Users/shikha/miniconda3/envs/carsus/lib/python3.7/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/shikha/miniconda3/envs/carsus/lib/python3.7/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/shikha/miniconda3/envs/carsus/lib/python3.7/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/Users/shikha/miniconda3/envs/carsus/lib/python3.7/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='physics.nist.gov', port=443): Max retries exceeded with url: /PhysRefData/ASD/Html/verhist.shtml (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)')))

### PR DESCRIPTION
**Pull request by s-rathi**
### :pencil: Description

**Type:** :beetle: `bugfix` 

Disable SSL certificate validation on NIST dataset download.

Closes #329 

### :vertical_traffic_light: Testing

How did you test these changes?

- [x] Testing pipeline
- [x] Other method (manually imported and tested the module)

### :ballot_box_with_check: Checklist

- [ ] I requested two reviewers for this pull request

### CODE REVIEW

**Comment by atharva-2001** [comment]
This isn’t safe, right?

**Comment by s-rathi** [comment]
It may leave you prone to some form of MITM Attack. However, in this case since the target url is fixed and we are sure that we are making request to HTTPS (although not verifying the certificates), a level of security is maintained.

Alternate solutions involve configuring the CA certificates, but that solution may require regular updates depending on the frequency at which the certificates for the NIST website update.

This PR fixes the issue with the usability of the app while suppressing any warnings. It is possible to implement an alternate solution, however it will involve maintaining third party certificates in the code, that's why I did not implement it.

**Comment by atharva-2001** [comment]
We can update the CA certificates programmatically, cant we?

**Comment by s-rathi** [comment]
Yes we can, but again it depends on the application design and everything has its pros and cons:
- Update the certificates during the application setup.
    - Drawback: Certificate can expire. So there need to be some way to update it periodically.
- Update certificates before making the request.
    - Drawback: This will make the requests logic unnecessarily complex.
- Maintain the certificates on GitHub.
    - Drawback: Certificate can expire. They need to be periodically updated. Furthermore, maintaining certificates on GitHub may cause backwards incompatibility with each release.

**Comment by atharva-2001** [comment]
I am inclined to agree, but the error also arises when we try to get GFALL data(at least in pipelines):
```
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /tardis-sn/carsus/master/carsus/tests/data/gftest.all (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get issuer certificate (_ssl.c:1091)')))
```
Here is the workflow that failed: https://github.com/tardis-sn/carsus/actions/runs/4404114803/jobs/7713322941

What do you think about this?

**Comment by s-rathi** [comment]
Yes that's right. The PyTest cases passed in my system so I did not consider the possibility of remaining failures while creating this PR.

image

We should handle these cases too.

The error is thrown when the application makes a request using [read_from_buffer()](https://github.com/tardis-sn/carsus/blob/master/carsus/io/util.py#L82-L108) utility function.

I think that we can consider disabling the certificate validation for this function too.

---

The reason why dynamically downloading certificates can be a bad idea:

If we dynamically configure the certificates, then it means that the application will download the certificates from a website (say example.com) and then use those certificates for validation. However, if an attacker is re-routing the traffic of example.com to attacker.com, in that case the application will download the certificates of attacker.com and use it to validate the connection to example.com->(routed to)->attacker.com, which will be verified as safe by the application. It means that the approach to dynamically download the certificates will be ineffective against the MITM attacks.

However, if we do not consider the security against network attacks as a non-functional requirement of the project, then it should be fine to skip certificate validation as long as we are sure that the website that we are requesting is on HTTPS.

**Comment by andrewfullard** [comment]
I think this is a reasonable solution. If we can't trust NIST, then we have bigger problems than Carsus users :)

**Review by epassaro — APPROVED** [review]

**Comment by atharva-2001** [comment]
Trying a few more times also seems to fix the issue: https://github.com/tardis-sn/carsus/pull/327/commits/01d61af6407ea1e1040e8c453dcca4773e78670d. This also seems like a reasonable solution to me, but I'm afraid turning off certificate validation is discouraged on various answers on stackoverflow.com, for example, [this](https://stackoverflow.com/a/12864892/11974464). These errors are also sporadic, trying a few more times would be a better solution I guess, rather than turning off certificate validation.

**Comment by s-rathi** [comment]
While multiple retries sound like something a user can do manually, hardcoding the retries to 10 may not be the best way to handle the issue.

**Comment by s-rathi** [comment]
I have updated the PR to handle the requests from `read_from_buffer()` utility function. It should handle the remaining cases.

**Review by chvogl — APPROVED** [review]
Thanks a lot for tackling this issue. The proposed solution should be safe enough for accessing NIST (as @andrewfullard and @epassaro stated).

**Comment by andrewfullard** [comment]
Thank you for the contribution @s-rathi but we're going to use the solution in #331 . We may revisit this PR if that solution is not sufficient.

**Pull request closed without merging**
