### PR TITLE
Mapping labels into levels for each ion

### PR DESCRIPTION
**Pull request by laureanomartinez**
### :pencil: Description

**Type:** :beetle: `bugfix`

Write a complete description of your changes, including the necessary context or any piece of information required to understand your work.

There is a problem when mapping `labels` into `level indexes`. Mapping is done for all ions simultaneously, but `labels` are not unique, and one could get some levels that are not included in the CMFGEN files. With this PR, `labels` are mapped within each ion.

Also, link issues affected by this pull request by using the keywords: `close`, `closes`, `closed`, `fix`, `fixes`, `fixed`, `resolve`, `resolves` or `resolved`. 

### :pushpin: Resources

Examples, notebooks, and links to useful references.

### :vertical_traffic_light: Testing

How did you test these changes?

- [x] Testing pipeline
- [ ] Other method (describe)
- [ ] My changes can't be tested (explain why)

### :ballot_box_with_check: Checklist

- [ ] I requested two reviewers for this pull request
- [ ] I updated the documentation according to my changes
- [ ] I built the documentation by applying the `build_docs` label

> **Note:** If you are not allowed to perform any of these actions, ping (@) a contributor.
@epassaro

### CODE REVIEW

**Comment by epassaro** [comment]
I think these changes are ok to fix the issue for now, but not sufficient.

The matching of lines-levels, collisions-levels, etc. should be done always in the output module.

I need to create a notebook to explain myself, I'll do it later this weekend.

**Comment by wkerzendorf** [comment]
@atharva-2001 @epassaro say - we need to dig a little deeper

**Comment by wkerzendorf** [comment]
@laureanomartinez - is this still active

**Comment by laureanomartinez** [comment]
Yes, this is still active. I'm sorry I could not contribute to this anymore, I had to finish writing my thesis as quickly as possible. Now my thesis is finished, so I'll be back to this.

**Comment by epassaro** [comment]
I'll pick up this in 1-2 weeks

**Comment by afloers** [comment]
@epassaro should this be closed?

**Pull request closed without merging**
