### PR TITLE
[GSoC] Compare versioned atomic data repositories

### PR DESCRIPTION
**Pull request by Ayyyn**
### :pencil: Description

**Type:**  :rocket: `feature`

As first objective's solution, this jupyter notebook generates 2 atom data files with two different versions of Chianti (here 9.0.1 and 10.0.1) and compares using` AtomDataCompare` class as part of carcus
### :pushpin: Resources
[Carsus Documentation](https://tardis-sn.github.io/carsus/)

Examples, notebooks, and links to useful references.

### :vertical_traffic_light: Testing

How did you test these changes?

- [ ] Testing pipeline
- [ ] Other method (describe)
- [ ] My changes can't be tested (explain why)

### :ballot_box_with_check: Checklist

- [ ] I requested two reviewers for this pull request
- [ ] I updated the documentation according to my changes
- [ ] I built the documentation by applying the `build_docs` label

> **Note:** If you are not allowed to perform any of these actions, ping (@) a contributor.

### CODE REVIEW

**Comment by Ayyyn** [comment]
@atharva-2001 @epassaro @wkerzendorf can you please review it?

**Comment by atharva-2001** [comment]
Can you share an NbViewer link?

**Comment by Ayyyn** [comment]
Sure, here's the link: 
https://app.reviewnb.com/tardis-sn/carsus/pull/335/

**Comment by chvogl** [comment]
Thanks for working on the GSOC first objective.

**Pull request closed without merging**
