### PR TITLE
Added BSD 3 Clause LICENSE.md file

### PR DESCRIPTION
**Pull request by hrithik18236**
## Motivation
Deals with Issue #194

### CODE REVIEW

**Comment by chvogl** [comment]
@hrithik18236 Thanks a lot for the PR. Please always request at least two reviewers for your PR so that people get notified.

**Comment by chvogl** [comment]
I think a BSD 3 license would make sense give that it is what we use in TARDIS. What do you think @epassaro @wkerzendorf @afloers?

**Comment by hrithik18236** [comment]
@chvogl Sure I will keep that in mind!

**Comment by epassaro** [comment]
I think it's up to Wolfgang. But we need to be sure we do not ship any piece of data from other projects (for example zeta data is currently included in carsus code).

**Comment by wkerzendorf** [comment]
PR #241 has the astropy license file

**Pull request closed without merging**
