### PR TITLE
Store ground levels from NIST Ionization energies

### PR DESCRIPTION
**Pull request by mishinma**
This PR:
 - Adds the `ground` boolean column to mark ground levels and the `ground_levels` relationship for `Ion`.
 - Implements a parsing grammar (using pyparsing) for parsing J values (and other stuff) from the "Ground Level" column. The grammar is implemented in `carsus/io/nist/ionization_grammar.py` and is well documented and tested.
 - Implements the `prepare_ground_levels_df` method for creating dataframes which contain ground levels data ([example](https://drive.google.com/file/d/0BxXCddocl9m3TktRd21qb0hNU00/view?usp=sharing)).
 - Implements the `ingest_ground_levels` method for storing the data in the database

Storing the ground levels data is necessary for creating artificial ions that have only ground level.

### CODE REVIEW

**Comment by wkerzendorf** [comment]
why do we have a ground flag, I don't see a need for this. The lowest level is just the ground level.

**Comment by mishinma** [comment]
Well, although it is possible to do without the ground flag it is much more involved. With the ground flag I defined a ground_levels relationship for Ion. I don't see now how to define this relationship without the flag because level energies are stored in another table (LevelQuantity).  So one would need to make a join to this table and find levels with energy 0.

**Comment by mishinma** [comment]
Which complicates it even more is the fact that several energies could be available for a level (that is why they are stored in another table) so there could be several rows for one level.

**Comment by mishinma** [comment]
@wkerzendorf do you agree with my reasoning? can I merge this PR?

**Comment by wkerzendorf** [comment]
@mishinma not really - let's discuss this in person. I just sent you a message on gitter

**Pull request closed without merging**
