### PR TITLE
added LICENCE issue: #192

### PR DESCRIPTION
**Pull request by parikshit14**
## Motivation

Added a LICENCE.md file which was needed in the repository. This PR solves the issue: #194 . Licence Template: BSD 3-Clause "New" or "Revised" License

## Changes
Only a new file `LICENCE.md` is added rest files are untouched 

## Description

The license that is added is BSD 3-Clause "New" or "Revised" License.

### CODE REVIEW

**Comment by chvogl** [comment]
@parikshit14 Please always request at least two reviewers.

**Comment by parikshit14** [comment]
Sorry, I forgot as it wasn't mentioned anywhere. Will keep this in mind next time.

**Comment by parikshit14** [comment]
@epassaro @wkerzendorf can you please review this PR

**Comment by chvogl** [comment]
Is the request reviewer option in the top right not available for you?
Screenshot 2021-03-30 at 14 39 43

**Comment by parikshit14** [comment]
> Is the request reviewer option in the top right not available for you?
> Screenshot 2021-03-30 at 14 39 43

it thought it would be mentioned when we create a pr, like that in case of tardis. There they have specified a field that asks you if you have contacted for reviewers or not. This is the reason why I didn't bother to ask for reviewers in this case. I hope it is ok.

**Pull request closed without merging**
