### PR TITLE
Carsus atomic data

### PR DESCRIPTION
**Pull request by PIYUSHgoyal16**
Created a class UPDATE_CMFGEN that downloads data from "http://kookaburra.phyast.pitt.edu/hillier/web/CMFGEN.htm" whenever the data is updated. It contains parsers(general for all OSC files) that remove the inconsistency of data and stores the data in tabular form. Done the testing using pytest and have added the tests. 

## Description
Created a class UPDATE_CMFGEN that downloads data from "http://kookaburra.phyast.pitt.edu/hillier/web/CMFGEN.htm" whenever the data is updated. The class maintains a LOG file for observing these changes. Then every file is processed using parsers. Parsers remove the inconsistency of data and stores the data in tabular form along with their metadata in the HDF5 format file. The following Flowchart helps in better understanding the workflow of the update function.
flow

## Motivation and Context
The motivation of this class was to automate the download of databases and update the data with the least manual interaction. 
The motivation of these parsers is to remove inconsistency from the data. The file contained two tables, that also has a different number of columns. There was data in between them as well. Moreover, there wasn't space between some of the attributes. Fixed these issues by developing a Regular Expression and using the same to extract metadata as well as tabular data.

## Screenshots
Screenshots of datatables obtained from "si2_osc_kurucz"
Screenshot from 2020-03-01 12-07-31
Screenshot from 2020-03-01 12-06-17

## How Has This Been Tested?
All functions have been tested using pytest. 
I have created a static webpage "https://my-static-site-exampl1601.herokuapp.com/test.html" for testing purpose only. The page is quite similar to CMFGEN HTML page and solves the testing purpose quite apprehensively.

## Future Aspect
1) Now I want to develop methods to create a version history of data, i.e. either by evaluating spectrums for the files or other method. 
2) Create Parsers for other types of files such as COL, PHOT, etc.

### CODE REVIEW

**Comment by PIYUSHgoyal16** [comment]
@afloers I have added the first future aspect, i.e. now the code downloads the zip file from the above url, unzips it, after extraction delete the zip file. Also the next time the script is called the program checks for the unzipped file. If it is present then no downloading takes place.

**Comment by afloers** [comment]
Please make sure that you keep the column names - it will be very important to know what the numbers / strings are.

The two tables contain very different information: the first table contains atomic levels, the second file transitions between atomic levels. The 'i-j' in the second table means that the transition is between the i and j levels as given in the first table. You can remove the '-' in between these (as well as in front of the level term (e.g.  -3s_3p2_4Pe).

In your changes you use string logic to disentangle the columns in table two. Try to find a regular expression that can do that - not all files in the database follow the same logic and sometimes spaces are used as separators. It will be easier to have a number of regular expressions for this.

**Comment by PIYUSHgoyal16** [comment]
I have added the names of the columns and removed the minus signs in the front and end. I have also used string logic to disentangle the columns by developing a Regular Expression.
Kindly review my PR and suggest further changes.

**Comment by afloers** [comment]
Can you please add additional documentation and a dedicated download/read method to your class?

**Comment by PIYUSHgoyal16** [comment]
@afloers I am working on that only. Once it is completed I will make a PR soon.

**Comment by PIYUSHgoyal16** [comment]
@afloers @wkerzendorf I have added a class Update_CMFGEN. The class contains a driver function update. It automatically updates all files present in all folders. Read updated files and extract_tabular_data from them and stores in a HDF5 file. All these procedures maintain the structure of folders. A detailed view of what I have done is provided by me in my proposal :)

Things that I have done but not mentioned in the proposal 
1) Make HDF5 files: I have made HDF5 files for all files maintaining the structure so that they can be easily accessed while retriving information.
2) Write data in HDF5 files
3) Include support of "tar" and "tar.gz" types of folders that are uploaded.
Other things are more or less same as provided in the proposal.

Shortcomings that will be fixed in coming time:
1) Names of columns are not extracted yet. I am reading more about the documentation of data in order to understand a pattern. I will soon be able to figure it out. Currently the names of the columns are the same as in "si2_osc_kurucz".
2) Write tests using pytest, currently I have tested the class manually only. I will soon write the tests for the same.

**Comment by afloers** [comment]
Nice! Have you inspected the results for other osc_files? They might have a slightly different structure and you might need to adapt your regex. This also means the columns have to be extracted for each file, as sometimes the structure is different. Sometimes files (e.g. osc_files, but also other types) are missing from a folder. 

Also, **visually** inspect the data you're parsing. Does it make sense? Has everything been parsed correctly? Then we need to think about how we can add tests to make sure there are no problems.

**Comment by PIYUSHgoyal16** [comment]
Sir I have checked for other osc_files also. My code works for them as well. You are correct they may have different structure. That issue is addressed by me by first extracting data lines that needs to be put into dataframe. Then I am dividing it into columns using another general regex expression.
You are right the column names may be different. But it is not feasible to pass the columns as input for each file. Hence we need to extract column names. For this I am searching for a pattern and will find it soon.
Which data are you asking me to visualise? Sorry I am unable to get it. If you are talking about paths, ya it is parsed correctly.
For adding tests I am writing a program that will search if the HDF5 files are present in the correct directory or not. This is the first test. You can advise me other tests also:) Hopefully we will implement them soon

**Comment by PIYUSHgoyal16** [comment]
@afloers You were correct the makeHDF5 function was called redundantly. Hence the structure wasn't preserved. i have corrected this bug. For testing I have created a static website on url "https://my-static-site-exampl1601.herokuapp.com/test.html". I am writing the test using pytest. Kindly highlight any issue regarding the same.

**Comment by afloers** [comment]
Sorry, that it wasn't very clear. 
Can you look at the parsed data to make sure that there are no errors?  E.g. energy levels are increasing, g-factor is a positive integer, level indices are increasing etc.

**Comment by PIYUSHgoyal16** [comment]
@afloers I have added all the tests. To make the tests realistic, I myself created a small static html page that is hosted on url : https://carsusatomicdatatest.herokuapp.com/test.html. I have tried to test each and every small function including is_same(). I have also added a test to check that all g values in first table are greater than zero.

**Comment by PIYUSHgoyal16** [comment]
@afloers I have created the general osc_parser that you were talking about. I have observed the pattern in some of the osc files and hopefully, it worked for all the files. I will write tests for the same soon. But now we can compare the data of si_ii ion for different dates. Kindly state what type of differences should I work on.

**Comment by PIYUSHgoyal16** [comment]
@epassaro @afloers Kindly give your review about the general osc parser. Also, let me know what could be the more functionalities that I could work on besides creating parsers for other types of files.

**Comment by PIYUSHgoyal16** [comment]
@epassaro I have created other parser for CMFGEN database as well. How should I proceed to add those changes? Should I proceed to create another PR?

**Comment by epassaro** [comment]
Reopened.

**Pull request closed without merging**
