### PR TITLE
Improvised osc file parser 

### PR DESCRIPTION
**Pull request by negswell**
**New Changes :**
Automatic download method has been added , which allows the user to download the database within the working directory directly from the script .As a precaution It will not download the file if it already exists in the working directory .
Progress bar for the download has also been added using tqdm .(aesthetic can be improved )
Header method has been added that allows the user to fetch the database details **without downloading the database** .
The details that can be fetched currently are

1. Last date modified 
2. Database/File Size 
3. Today's date (for comparison)
4. File Content type 

**The CMFGEN parser for the osc files has been completely re written . Supports all osc files .
The changes in the new parser are** 
1.No need to extract the databse anymore ,the database zip file has to be present within the working directory or can be download to the working directory using the new download function .
2. The database will be read without extraction , find row function has been deprecated to parse the data within one pass of the data file .
3. to_hdf() method within the class now takes an explicit  fname parameter which can be used to create the hdf while in the passed file path . Default path will be the working directory .
4. parse_header function no longer requires the key to be passed explicitly . The new improvised method finds the keys using regex on it's own and will return a dict of the keys and its respective values .
 
**Important changes to be Made :**

1.  Inherit the new modified  classes from the base class .(will be made soon)
2. Add dynamic parsing for download function .
3. pprint the self.meta attribute (if needed for better aesthetic )
4. Other parsers have to be modified as well to the new logic .

Screenshot from 2020-03-27 16-28-07
Screenshot from 2020-03-27 16-31-02
Screenshot from 2020-03-27 16-32-31
Screenshot from 2020-03-27 17-31-45

### CODE REVIEW

**Comment by negswell** [comment]
unable to inherit base parser since crasus.io.base , raises module error ,has  forced me to model my parser on the base parser instead without inheritance .
i am unsure how backward import has been achieved in existing parsers .
fix suggested, is to use the path of the base class in the import to ensure no import errors .

**Comment by afloers** [comment]
FYI it's carsus not crasus

**Comment by afloers** [comment]
Can you please do some tests that show that you get the same results?

**Comment by negswell** [comment]
> Can you please do some tests that show that you get the same results?

hi yes i have built it manually , tested it too , do i upload the screenshots ?

**Comment by negswell** [comment]
> FYI it's carsus not crasus

oo yes apologies :)

**Comment by afloers** [comment]
Just add them to your pr, it makes it easier to look at things.

**Comment by negswell** [comment]
> Just add them to your pr, it makes it easier to look at things.

yes i'll upload them now

**Comment by negswell** [comment]
> > FYI it's carsus not crasus
> 
> oo yes apologies :)

rom carsus.io.base import BaseParser
ModuleNotFoundError: No module named 'carsus'

i still face this issue i can specify the path to carsus explicitly  to remove the error from the import , if inheritance from base class is essential .

**Comment by negswell** [comment]
The outputs are below  ,there was a small bug , i have patched it now.
[](https://ibb.co/0tSw6cB)
[](https://ibb.co/4WZ4mLy)
[](https://ibb.co/Xx53rp4)
[](https://ibb.co/VWg8ygD)

**Pull request closed without merging**
